# Site settings
title: DobroStan | Kurs Mindfulness | Psychoterapia | Gdańsk
email: magda.dlugolecka@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  DobroStan Mindfulness i Psychoterapia
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dobrostan.org.pl"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
